title: 照片集
subtitle: Take Photo Think Seriously
description: 拿起相机，认真思考
cover: 'https://github.com/lfkdsk/picx-images-hosting/raw/master/20230817/IMG_7586.4e91my1ve140.17iz0sa56gik.webp'
author: DonkeyKane

footer_logo: 
  use: self
  self:
    link: 'https://xiaolin2004.github.io/my_blog'
    src: 'https://github.com/lfkdsk/picx-images-hosting/raw/master/20230817/tripper2white.2pbuwaqvndu0.webp'

url: https://xiaolin2004.github.io/gallery
root: /gallery

photography_page:
  slogan: true
  slogan_descr: 'DK的日常影集'
  travel_slogan: true
  travel_slogan_descr: ''

google_analytics: 
  use: gtag
  ga_id: 
  ga_api: 
  gtag_id: G-8TMSDJG47Q

follow_challenge:
  feedId: "55889147392629760"
  userId: "41784388753060864"

nav:
  地图:
    link: /gallery/location
    icon: local-two
  归档: 
    link: https://xiaolin2004.github.io/my_blog
    icon: inbox
  随机:
    link: /gallery/random
    icon: pic
  # 查询:
  #   link: /gallery/query
  #   icon: history-query
  状态监控:
    link: /gallery/status
    icon: list-view
  时间线:
    link: /gallery/grid-all
    icon: grid-nine

thumbnail_url: https://cdn.jsdelivr.net/gh/xiaolin2004/gallery/thumbnail/
base_url: https://raw.githubusercontent.com/xiaolin2004/gallery/master
backup_base_url: https://cdn.jsdelivr.net/gh/xiaolin2004/gallery/master
backup_thumbnail_url: https://raw.githubusercontent.com/xiaolin2004/gallery/thumbnail/
